### ISSUE TITLE
低照度图像的合成代码在哪块啊？

### ISSUE THREAD

**Issue by mvpzhangqiu** [cuiziteng/ICCV_MAET#11]

**Comment by cuiziteng** [comment]
https://github.com/cuiziteng/ICCV_MAET/blob/master/mmdet/models/detectors/MAET_YOLO/MAET_YOLO.py

**Comment by fireinth** [comment]
您好，请问您把这个模块成功利用了吗，可以指点一下吗，这块有点问题运行不了了
