### ISSUE TITLE
Fine-tuning on Dark Face

### ISSUE THREAD

**Issue by Dzp1007** [cuiziteng/ICCV_MAET#12]
Dear author, thank you so much for the brilliant work! 
I tried to reimplement your results on Dark Face following your instructions but got some bad results (an mAP of 0.2 on your val split). Since setting up the fine-tuning step is very simple by only modifying the paths to Dark Face dataset and pretrained model, I am very confused what goes wrong. Could you please share some advice? Thank you.

**Comment by cuiziteng** [comment]
Hello, please check these:

(1) Could you get my results on Dark-Face use our pre-train model.

(2) Have you load the correct pre-train model? Or have you change the config file?

**Comment by cuiziteng** [comment]
Maybe, you use the different version of UG2 dataset, since I use the first version UG2 dataset, so maybe you use the newer version UG2 dataset?

**Comment by cuiziteng** [comment]
If the EXDark results you run is OK, right? 

I'll check it after the CVPR ddl and reply to you later~

**Comment by cuiziteng** [comment]
Sorry for the late reply, I've check and confirm that the results isn't wrong, the command is:

<img width="962" alt="image" src="https://user-images.githubusercontent.com/55396225/202233468-90b06893-bb43-4477-b0c3-3a189db22f6f.png">

and the results should be:

<img width="523" alt="image" src="https://user-images.githubusercontent.com/55396225/202233567-eeae9d26-18e5-4087-97ca-075c42edf960.png">

Please confirm that you get same mmdetection version and mmcv version.
<img width="858" alt="image" src="https://user-images.githubusercontent.com/55396225/202233712-603f70b3-f567-405f-a25f-d759cd3593b3.png">. And the command should be same as mine.

Thanks for your interests in my paper, any question please drop here ~
