### ISSUE TITLE
Download link for UG2_DarkFace Pre-Trained Model Broken

### ISSUE THREAD

**Issue by aasharma90** [cuiziteng/ICCV_MAET#14]
Hi, 

Thanks for sharing your work. 

Could you please look into the download link of your pre-trained model on the DarkFace dataset? 
The google drive link is broken and the baidu link keeps on loading. Thanks!

**Comment by cuiziteng** [comment]
Hi, new link uploaded, please check ~

**Comment by aasharma90** [comment]
Hi, 
Thanks for releasing the model.
