### ISSUE TITLE
Question on implementation of ort_loss

### ISSUE THREAD

**Issue by DFSDDDDD1199** [cuiziteng/ICCV_MAET#17]
Hi,

The ort_loss is implemented in MAET_YOLO.py as 
<img width="1182" alt="截屏2023-03-16 下午10 14 27" src="https://user-images.githubusercontent.com/61130989/225644843-265dd4ce-28aa-4755-b35b-353d384b2cea.png">.
The first term is the cosine simularity between dLoss/dLight_Feature and dLoss/dDark_feature, while the second and third terms seem to equal to zero, which seems to be inconsistent with version in the paper.
<img width="597" alt="截屏2023-03-16 下午10 15 52" src="https://user-images.githubusercontent.com/61130989/225645076-e5d933ca-cd9d-42f9-84b7-41c03f4ef0da.png">
Could you help me understand how the ort_loss in the paper is converted into its implementation version?

**Comment by cuiziteng** [comment]
Hi, thanks for your interest in this paper ~

The function in the paper is a cos similarity loss, which hopes to minimize the cos similarity between the two different features.
<img width="343" alt="image" src="https://user-images.githubusercontent.com/55396225/225843164-95ee67de-aaf7-437e-9472-a2d76c98e055.png">

BTW, the last 2 equation hope to enlarge the cos similarity of the same features, they could also be seem as a part of equation (4) in the paper. 
<img width="637" alt="image" src="https://user-images.githubusercontent.com/55396225/225843504-b21b5b00-9aff-454f-abea-7288e297f6d1.png">

**Comment by cuiziteng** [comment]
Hello, thanks for the interest in this paper ~

Only the first part is the cosine similarity between two features.
<img width="573" alt="image" src="https://user-images.githubusercontent.com/55396225/225848529-38da16cb-0473-4410-a045-686332dc2b50.png">
<img width="323" alt="image" src="https://user-images.githubusercontent.com/55396225/225848680-8cd000dd-3693-43b0-9191-a470d0b5872d.png">

The following parts should be 0 in this loss, I added them just hope to prevent some bug may occur in torch ~
<img width="622" alt="image" src="https://user-images.githubusercontent.com/55396225/225848927-b47222c1-3112-4adc-9d99-f4a7bf7d00e4.png">
