### ISSUE TITLE
Download link of pretrained ExDark baseline model

### ISSUE THREAD

**Issue by farhannz** [cuiziteng/ICCV_MAET#18]
Hello, 
Thanks for your work.   

I'm trying to download the pre-trained ExDark baseline model, but it doesn't seem to have the GDrive link.
Could you please look into it? Thanks.

|  dataset   | model  | size | logs |
|  ----  | ----  | ----  | ----  |
| EXDark (76.8) 20 class | ([google drive]) ([baiduyun](https://pan.baidu.com/s/1WRqXA8-Tal7WFtIt-2v0jA), passwd:1234) | 470.26 MB | - |

**Comment by cuiziteng** [comment]
Thanks for your interest ~

The model has been uploaded, please check ~

**Comment by farhannz** [comment]
Thanks for uploading the model.
