### ISSUE TITLE
about ZERO DCE

### ISSUE THREAD

**Issue by PeterSmith1** [cuiziteng/ICCV_MAET#19]
作者大大，我看你配置文件有zero dce-yolo,但我在配置文件代码里并没有看到有zero dce得相关代码，这部分代码是没有上传吗？

**Comment by cuiziteng** [comment]
那个是用zero-dce算法预处理后的图像，然后跑的YOLO，我把增强后的图像一起放到数据集里了。

<img width="867" alt="image" src="https://user-images.githubusercontent.com/55396225/235180289-2934cf8a-cd30-49ea-9cc8-376e3968781c.png">
