### ISSUE TITLE
exdark相关评价指标

### ISSUE THREAD

**Issue by LiChangYu1997** [cuiziteng/ICCV_MAET#20]
您好，请问在本项目实施过程中对ExDark数据集的mAP指标采用的是mAP0.5还是mAP0.5-0.95，我在最初理解本项目时认为采用了mAP0.5，但在一篇论文中有关ExDark数据集上的结果与我的理解产生了矛盾https://www.mdpi.com/1424-8220/22/10/3703#B11-sensors-22-03703

**Comment by cuiziteng** [comment]
您好，感谢关注，本文中EXDark数据集的评价指标是与VOC数据集相同，mAP0.5，请参考这部分[代码](https://github.com/cuiziteng/ICCV_MAET/blob/67a4b98fdf700d0186e4da78f8ea28d21f484667/mmdet/datasets/Exdark.py#L206)。

**Comment by LiChangYu1997** [comment]
您好，我发现在项目中在ExDark数据集上的mAP指标为77.8，而在论文中为74.0，两次指标有何差别，若我希望在论文中引用您的工作应按照哪个指标
