### ISSUE TITLE
Question about Exdark Training data

### ISSUE THREAD

**Issue by MingboHong** [cuiziteng/ICCV_MAET#22]
Hi~ Thank you for sharing your amazing work!
I downloaded Exdark data from https://github.com/cs-chan/Exclusively-Dark-Image-Dataset, and I found that the Exdark dataset is divided into 3 parts (training, val, and test), where the training part only contains 3000 images. However, it seems MAET's training dataset didn't follow this division (val:1467 training:5896).

**Comment by cuiziteng** [comment]
Hello, thanks for your interest and attention!

In fact, my paper MAET was accepted by ICCV in 2021, and maybe they divided their dataset in 2022, so there maybe a time gap, you could follow both settings is OK.
<img width="437" alt="image" src="https://github.com/cuiziteng/ICCV_MAET/assets/55396225/feba69d9-6283-4ad5-b940-1187a71ecea7">

**Comment by MingboHong** [comment]
> Hello, thanks for your interest and attention!
> 
> In fact, my paper MAET was accepted by ICCV in 2021, in that year the EXDark dataset did not divide data, and maybe they divided their dataset in 2022, so there may be a time gap, you could follow both settings is OK.
> 
> <img alt="image" width="437" src="https://user-images.githubusercontent.com/55396225/268512656-feba69d9-6283-4ad5-b940-1187a71ecea7.png">

got it, thx for your reply~
