### ISSUE TITLE
train.py: error: unrecognized arguments: --load-from modelpth/epoch_273.pth

### ISSUE THREAD

**Issue by Panhonganadd** [cuiziteng/ICCV_MAET#23]
![image](https://github.com/cuiziteng/ICCV_MAET/assets/147368008/8ab2290b-117f-4290-a31f-955f1d5904d0)

你好，我再训练的时候出现了这个错误，请问该怎么解决？

**Comment by cuiziteng** [comment]
您用的可能是新版的mmdet? 版本没有匹配吧，用--resume-from可以吗

**Comment by Panhonganadd** [comment]
问题已解决，万分感谢！

**Comment by cuiziteng** [comment]
您客气了
