### ISSUE TITLE
您好，想请教您几个问题

### ISSUE THREAD

**Issue by zxy1825** [cuiziteng/ICCV_MAET#25]
大佬好，很受您的这篇文章的启发，有几个问题想要请教您
1. 在您的论文Table3中有提到，您使用三种方法增强后，YOLO(N)微调后检测结果能够达到65%+，包括MAET能够达到74%，能详细说一下细节吗，比如如何划分的训练/验证？因为我是用yolov5l做的，MEBBLN和ZeroDCE才堪堪达到63左右，如果还好找的话，您能提供一下yolov3的权重文件就最好啦！
2. 关于环境，您是否能详细说说使用的全部版本信息，包括mmcv，pytorch和cuda，因为注意到您的README中说的mmcv使用的是1.1.5，实际安装后运行MAET时会报错并让我安装2.0.0rc4，如下
 `AssertionError: MMCV==1.1.5 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.2.0.`
安装完这个pytorch又报错......所以不知您是否能找到当时使用的版本信息我核对一下~
感谢，期待您的回复！

**Comment by cuiziteng** [comment]
您好，非常感谢您的关注～

1. 第一点的原因：（1）您用的是ImageNet Pretrain模型而不是COCO Pretrain模型，您可以换成YOLO-V5 COCO Pretrain实验一下，我觉得点数只会比YOLO-V3更高不会低。（2）您的训练超参数没有调整，比如epoch number等方面也许可以更大之类的。

2. 这个工作是两年前我在上海交大的硕士期间的工作了，当时基于的mmdet版本是2.7.0， mmcv版本是1.1.5:
https://github.com/open-mmlab/mmdetection/tree/v2.7.0 ，您需要按照匹配的pytorch版本，如1.6.0，最好CUDA版本也是10.1或者10.2。

由于mmdet的版本更迭，如果您这边实在因为环境或者CUDA版本问题无法实现，因此还是建议您用mmdet2.0自己重新build一下，要不然的话环境这块会很麻烦。

**Comment by zxy1825** [comment]
好的，感谢您的解答！
