### ISSUE TITLE
有关实验结果的确认

### ISSUE THREAD

**Issue by ghost** [cuiziteng/ICCV_MAET#26]
作者您好！我最近学习了您MAET这篇工作的论文与代码，在实验过程中得到了一些不同的结果：MAET方法得到的结果的确有涨点；但是只在COCO数据集上进行预训练的YOLOv3在ExDark数据集上经过微调后也很容易就得到了不错的结果，也就是YOLO（N）得到了0.744的mAP，相比论文中报告的0.627似乎有一些差异，我仔细check了一下代码，在训练策略、数据处理等各部分是与源代码一致的，只是更换了加载的预训练权重文件。而且基于Kind、ZeroDCE这些方法的最后表现几乎与YOLO（N）没有区别，甚至反而有下降，所以有些不知所措了。

**Comment by ghost** [comment]
不过我是在最新的MMDetection版本上跑的，不知道是不是其相比较之前版本在训练以及一些其他方面做了改进，从而导致了结果的提高，因为我也是刚刚接触这些东西，所以想请教学习一下

**Comment by cuiziteng** [comment]
I'm sorry, the ICCV 2021 paper's results are changed, the renewed results I provide in the README.md

Please check ~

<img width="1013" alt="image" src="https://github.com/cuiziteng/ICCV_MAET/assets/55396225/664a6287-f40f-4b94-9e60-7755b97b931b">

**Comment by ghost** [comment]
非常感谢，是我没有注意到README文件更新后的baseline结果，谢谢你！
