### ISSUE TITLE
为什么MMDetcetion和Ultralytics训练出来的yolov3表现不一致

### ISSUE THREAD

**Issue by ghost** [cuiziteng/ICCV_MAET#27]
作者您好！我最近做实验有些疑问哈，想和您请教一下，不知道你之前有没有遇到这个问题。就是之前我用MMDetection做实验得到的结果和您更新后的结果是基本一致的，但是这两天我用Ultralytics的yolov3进行训练，就是在普通COCO数据集上进行训练然后再ExDark上进行微调，最后只得到下面这样的结果，学习率最后都逐渐缩小到1e-5了，但mAP只有0.559，和之前用MMDetection训练的0.75差距很大，所以很是疑惑，用MMDetection测试的那个VOC的mAP指标应该也是指mAP50-95吧？还是说那个mAP是指mAP50呢？麻烦您啦！

> Class     Images  Instances          P          R             mAP50   mAP50-95
> all         1467      4865                 0.83      0.786      0.846      0.559

**Comment by ghost** [comment]
这个是我MMDetection的test_cfg的配置，是不是它最后计算的就是mAP50呀
test_cfg=dict(
        nms_pre=1000,
        min_bbox_size=0,
        score_thr=0.05,
        conf_thr=0.005,
        nms=dict(type='nms', iou_threshold=0.5),
        max_per_img=100))

**Comment by ghost** [comment]
我刚仔细看了下代码似乎MMDetcetion的VOC Metrics的确是测试mAP50，这样看的话好像利用Ultralytics开源的代码训练效果会好一点呢！

**Comment by cuiziteng** [comment]
嗯嗯，非常感谢您的关注，MMDetection的metric是mAP50，这样看来Ultralytics相比mmdetection的提升非常明显。
