### ISSUE TITLE
Pre-trained Model for UG2+ DARK FACE

### ISSUE THREAD

**Issue by daooshee** [cuiziteng/ICCV_MAET#4]
Hi, thanks a lot for your excellent work! Could you please release the pre-trained model or training/testing code for UG2+ DARK FACE (Table 4 in your paper)?

**Comment by cuiziteng** [comment]
Thanks for your interesting!
I am very busy writing papers recently, and will provide code and models later～(mostly after CVPR)

**Comment by daooshee** [comment]
OK. Thanks so much for your quick reply!

**Comment by cuiziteng** [comment]
Hiii, sorry for the delay, I've upload the UG2 pre-train model and code of this project~

**Comment by daooshee** [comment]
Thank you~~
