### ISSUE TITLE
关于训练结果

### ISSUE THREAD

**Issue by Bigtuo** [cuiziteng/ICCV_MAET#5]
你好，我用你的代码重新训练并在一个新的夜景数据集上微调，去对比利用YOLOV3直接训练夜景图像，两者并无差异，甚至效果低于直接训练，这是否与某些超参数设置有关，该如何处理（样本类别：car,标注正常，数据集5000左右）

**Comment by cuiziteng** [comment]
你可以试试把网络head和neck部分裁剪掉，只用pre-train的backbone试一下，因为你只有一个类别，我这边实验结果来看用MAET的微调肯定会好于直接训练（在单类别的UG2-Dark Face上），如果你场景的光照都是极暗，你也可以尝试在pre-train的合成图像步骤调节k的阈值。

**Comment by Bigtuo** [comment]
好的，我试试，谢谢你的回复



---原始邮件---
发件人: "Cui ***@***.***&gt;
发送时间: 2021年11月8日(周一) 下午2:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cuiziteng/ICCV_MAET] 关于训练结果 (Issue #5)




 
你可以试试把网络head和neck部分裁剪掉，只用pre-train的backbone试一下，因为你只有一个类别，我这边实验结果来看用MAET的微调肯定会好于直接训练（在单类别的UG2-Dark Face上），如果你场景的光照都是极暗，你也可以尝试在pre-train的合成图像步骤调节k的阈值。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by cuiziteng** [comment]
要是为了更多涨点，你也可以试试在fine-tune阶段加一些数据增强，比如把论文中那些控制光照的环节做为数据增强加到fine-tune阶段，看看效果。

**Comment by cuiziteng** [comment]
或者你直接用EXDark这个model fine-tune? 试试效果？

**Comment by Bigtuo** [comment]
好的 ^_^



---原始邮件---
发件人: "Cui ***@***.***&gt;
发送时间: 2021年11月8日(周一) 下午2:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cuiziteng/ICCV_MAET] 关于训练结果 (Issue #5)




 
要是为了更多涨点，你也可以试试在fine-tune阶段加一些数据增强，比如把论文中那些控制光照的环节做为数据增强加到fine-tune阶段，看看效果。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by cuiziteng** [comment]
主要是之前faster-rcnn模型因为空间不够删了好多，那个点数更猛，没法发给你qaq

**Comment by Bigtuo** [comment]
其实我还有一个困惑，您用maet训练后的模型再用于单独yolo模型上微调，这样对比直接在yolo模型上训练有什么优势，为什么最终两个结果不会一致，等待您的答复



---原始邮件---
发件人: "Cui ***@***.***&gt;
发送时间: 2021年11月8日(周一) 下午2:33
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cuiziteng/ICCV_MAET] 关于训练结果 (Issue #5)




 
主要是之前faster-rcnn模型因为空间不够删了好多，那个点数更猛，没法发给你qaq
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by cuiziteng** [comment]
其实这个论文里面已经说了，（1）我们首先是在合成和真实数据集上面同时做测试（2）原有的模型都是在COCO正常光照图像上fine-tune，这样会有一个domain incosistancy，然而暗光图像缺乏这样的大型数据集，所以利用暗光合成手段和自监督学习重新做pre-train的话会提升暗光下的泛化性能，这样做fine-tune更好的使真实世界数据集效果提升。这个在论文的Table.3/4结果中也有体现。

**Comment by cuiziteng** [comment]
后续也可以针对fine-tune去设计一些结合物理模型的domain adaptation拓展，我现在在赶论文太忙了，之后可以多讨论

**Comment by Bigtuo** [comment]
好的，谢谢，感谢作者大大



---原始邮件---
发件人: "Cui ***@***.***&gt;
发送时间: 2021年11月8日(周一) 下午3:12
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cuiziteng/ICCV_MAET] 关于训练结果 (Issue #5)




 
其实这个论文里面已经说了，（1）我们首先是在合成和真实数据集上面同时做测试（2）原有的模型都是在COCO正常光照图像上fine-tune，这样会有一个domain incosistancy，然而暗光图像缺乏这样的大型数据集，所以利用暗光合成手段和自监督学习重新做pre-train的话会提升暗光下的泛化性能，这样做fine-tune更好的使真实世界数据集效果提升。这个在论文的Table.3/4结果中也有体现。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Bigtuo** [comment]
作者大大，又打扰到您学习了，原谅我太笨了，想了好久还是转不过这个弯！。
您说的暗光缺少这么大的训练集才采用这种自监督方法来训练预训练模型，这样的模型对暗光数据集泛化更加友好。是不是我采用5000张只有car类的正常光数据集（不用coco）重新训练maet，再进行暗光下（5000张）的微调是作用不大的（对maet训练数据太少）。
而且暗光下car类灯光这个特征比较明显（灯光影响也比较大的话，直接用yolo训练结果差距更小？）。
（因为我不管用何种方式训练，结果都差不多一样，包括基于yolo正常光训练，暗光微调。不过用了zerodce处理反而降低了）
还有，maet测试也是输入正常光吧，它也经过了低光合成操作（代码里有两个测试，simple test与aug test，只用到了simple test吧），T_T
希望得到您的回复！



---原始邮件---
发件人: "Cui ***@***.***&gt;
发送时间: 2021年11月8日(周一) 下午3:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cuiziteng/ICCV_MAET] 关于训练结果 (Issue #5)




 
后续也可以针对fine-tune去设计一些结合物理模型的domain adaptation拓展，我现在在赶论文太忙了，之后可以多讨论
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by cuiziteng** [comment]
是的，maet是在正常图像上大规模数据集上预训练效果明显，不加pre-train model或者少量数据pre-train效果肯定不会很理想。

灯光特征明显的话我估计就涉及到另一个问题了，你可以看看robby tan的那篇cvpr (Nighttime Visibility Enhancement by Increasing the Dynamic Range and Suppression of Light Effects)，不知道能不能对你有所启发。

**Comment by Bigtuo** [comment]
好的谢谢



---原始邮件---
发件人: "Cui ***@***.***&gt;
发送时间: 2021年11月11日(周四) 晚上11:02
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cuiziteng/ICCV_MAET] 关于训练结果 (Issue #5)




 
是的，maet是在正常图像上大规模数据集上预训练效果明显，不加pre-train model或者少量数据pre-train效果肯定不会很理想。
 
灯光特征明显的话我估计就涉及到另一个问题了，你可以看看robby tan的那篇cvpr (Nighttime Visibility Enhancement by Increasing the Dynamic Range and Suppression of Light Effects)，不知道能不能对你有所启发。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Bigtuo** [comment]
作者大大，打扰您了！
训练模型，我换了个对象进行测试（无灯光影响的），效果好一点，但其他结果有如下：用正常光训练，后暗光微调，结果比直接用暗光数据训练效果好，这是为什么呢？
（而且微调模型时，它首先在一个精度位置上下震荡（3个点左右），然后突然下降6个点后，持续上升，最后收敛，这样的情况正常吗？）
另一个问题，降低k值，需要调整其他参数值吗？



---原始邮件---
发件人: "Cui ***@***.***&gt;
发送时间: 2021年11月11日(周四) 晚上11:02
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cuiziteng/ICCV_MAET] 关于训练结果 (Issue #5)




 
是的，maet是在正常图像上大规模数据集上预训练效果明显，不加pre-train model或者少量数据pre-train效果肯定不会很理想。
 
灯光特征明显的话我估计就涉及到另一个问题了，你可以看看robby tan的那篇cvpr (Nighttime Visibility Enhancement by Increasing the Dynamic Range and Suppression of Light Effects)，不知道能不能对你有所启发。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by cuiziteng** [comment]
第一个可能是数据量问题，第二个微调时候震荡剧烈可能是实验setting没设置对，你可以给我发邮件详细说一下。

**Comment by Bigtuo** [comment]
作者大大，具体的我发您这上面了！
***@***.***

---原始邮件---
发件人: "Cui ***@***.***&gt;
发送时间: 2021年11月17日(周三) 晚上10:47
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cuiziteng/ICCV_MAET] 关于训练结果 (Issue #5)




 
第一个可能是数据量问题，第二个微调时候震荡剧烈可能是实验setting没设置对，你可以给我发邮件详细说一下。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
