### ISSUE TITLE
Some typos in the 'maet_yolo_coco_ort.py'

### ISSUE THREAD

**Issue by leonmakise** [cuiziteng/ICCV_MAET#6]
https://github.com/cuiziteng/ICCV_MAET/blob/ba1f49bdffa5f813052a9c296d17e1cecd3a5733/configs/MAET_yolo/maet_yolo_coco_ort.py#L4 
Here, should it be 'MAET_YOLO'?

https://github.com/cuiziteng/ICCV_MAET/blob/ba1f49bdffa5f813052a9c296d17e1cecd3a5733/configs/MAET_yolo/maet_yolo_coco_ort.py#L48
There should be another ')' .

**Comment by cuiziteng** [comment]
My code error, thx~

**Comment by cuiziteng** [comment]
My code error, thx~
Do ont Affect Usage~
